CREATE TABLE IF NOT EXISTS category (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(120) NOT NULL);

CREATE TABLE IF NOT EXISTS products (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
product_title VARCHAR(120) NOT NULL,
price DECIMAL(10, 2),
product_info TEXT,
discount DECIMAL(10, 2),
category_id BIGINT,
storage_id BIGINT,
FOREIGN KEY (category_id) REFERENCES category(id),
FOREIGN KEY (storage_id) REFERENCES storage(id));

CREATE TABLE IF NOT EXISTS storage (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
product_id BIGINT,
amount BIGINT NOT NULL,
FOREIGN KEY (product_id) REFERENCES products(id));

CREATE TABLE IF NOT EXISTS shop_users (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
username VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
phone_number VARCHAR(20) NOT NULL,
role VARCHAR(20) NOT NULL);
